module.exports = {
  ROLES: {
    SUPER_ADMIN: 'super_admin',
    COMPANY_ADMIN: 'company_admin',
    PROJECT_MANAGER: 'project_manager',
    TEAM_LEAD: 'team_lead',
    DEVELOPER: 'developer',
    QA: 'qa',
    HR: 'hr',
    CLIENT: 'client',
  },
  PERMISSIONS: {
    MANAGE_COMPANY: 'manage_company',
    MANAGE_USERS: 'manage_users',
    MANAGE_PROJECTS: 'manage_projects',
    MANAGE_TASKS: 'manage_tasks',
    MANAGE_TEAMS: 'manage_teams',
    VIEW_REPORTS: 'view_reports',
    MANAGE_SETTINGS: 'manage_settings',
    MANAGE_ROLES: 'manage_roles',
    MANAGE_ATTENDANCE: 'manage_attendance',
    MANAGE_LEAVE: 'manage_leave',
    MANAGE_INVOICE: 'manage_invoice',
    MANAGE_EXPENSES: 'manage_expenses',
    MANAGE_CLIENTS: 'manage_clients',
    MANAGE_KNOWLEDGE_BASE: 'manage_knowledge_base',
    MANAGE_ANNOUNCEMENTS: 'manage_announcements',
  },
  ROLE_PERMISSIONS: {
    super_admin: [
      'manage_company', 'manage_users', 'manage_projects', 'manage_tasks',
      'manage_teams', 'view_reports', 'manage_settings', 'manage_roles',
      'manage_attendance', 'manage_leave', 'manage_invoice', 'manage_expenses',
      'manage_clients', 'manage_knowledge_base', 'manage_announcements',
    ],
    company_admin: [
      'manage_company', 'manage_users', 'manage_projects', 'manage_tasks',
      'manage_teams', 'view_reports', 'manage_settings', 'manage_attendance',
      'manage_leave', 'manage_invoice', 'manage_expenses', 'manage_clients',
      'manage_knowledge_base', 'manage_announcements',
    ],
    project_manager: ['manage_projects', 'manage_tasks', 'manage_teams', 'view_reports'],
    team_lead: ['manage_tasks', 'view_reports'],
    developer: ['manage_tasks'],
    qa: ['manage_tasks'],
    hr: ['manage_attendance', 'manage_leave', 'view_reports'],
    client: [],
  },
};
